# Generated by Django 3.2.5 on 2021-07-29 17:13

import art_gallery_web.gallery_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('height', models.IntegerField(validators=[art_gallery_web.gallery_app.models.is_negative])),
                ('width', models.IntegerField(validators=[art_gallery_web.gallery_app.models.is_negative])),
                ('price', models.FloatField(validators=[art_gallery_web.gallery_app.models.is_negative])),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='arts')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery_app.arts')),
            ],
        ),
    ]
